server:
  servlet:
    context-path: /customerRegistration/api

spring:
  data:
    mongodb:
      uri: mongodb+srv://emanuel2017henrique:manu1097@customerregistrationdat.f6gqk.mongodb.net/customerRegistrationDataBase

springdoc:
  swagger-ui:
    path: /swagger-ui.html

