server:
  servlet:
    context-path: /customerRegistration/api

spring:
  data:
    mongodb:
      uri: mongodb+srv://emanuel2017henrique:vJ4dIs3tnjxR8LMH@customerregistrationdat.f6gqk.mongodb.net/nomeDoBanco?retryWrites=true&w=majority


springdoc:
  swagger-ui:
    path: /public/swagger

